export const RUNTIME_EXCEPTION_ON_INVALID_REFERENCE = 0;
export const EXCEPTION_ON_INVALID_REFERENCE = 1;
export const NULL_ON_INVALID_REFERENCE = 2;
export const IGNORE_ON_INVALID_REFERENCE = 3;
export const IGNORE_ON_UNINITIALIZED_REFERENCE = 4;
